Now takes cobra.Command directly
ctessum/gobra pull request #4
Opened 2017-10-30 18:47 UTC by khoin

This PR includes:

* Taking cobra.Command directly instead of specifying our own gobra.Command. This is possibly by wrapping a cobra.Command like so:

```go
c := gobra.CommandFromCobra{ cmd.Root } // where cmd.Root is of type cobra.Command
// c.Render() will generate an HTML snippet like before.
```

This PR shouldn't include previous commits... :crossed_fingers:

2017-10-30 20:23 UTC, ctessum requested changes
Looks good! Just a couple changes

2017-10-30 20:23 UTC, ctessum commented on example/cmd/cmd.go
> +	// static specifies whether the simulation should be run with a static
Outdated comment

2017-10-30 20:23 UTC, ctessum commented on example/cmd/cmd.go
> +This file is part of InMAP.
Change this license information to whatever the license is for this package

2017-10-30 20:23 UTC, ctessum commented on example/cmd/cmd.go
> +	Long: `steady runs InMAP in steady-state mode so nothing goes out of stability.`,
outdated text

2017-10-31 16:56 UTC, khoin commented
I've updated the out-dated texts.

2017-10-31 21:41 UTC, ctessum commented
Thanks. As one last thing, can you combine the three commits into one?

2017-10-31 23:58 UTC, khoin commented
Can't push to GitHub after squashing. I'll close this PR, delete branch (from GitHub), squash locally, push branch (to GitHub), then PR again.

2017-10-31 23:58 UTC, closed without merging

2017-11-01 04:10 UTC, ctessum commented
In the future you can do `git push -f origin branchname` to force the rewriting of the github version

2017-11-01 04:11 UTC, khoin commented
Wow thanks! That'll be really handy.

On Tue, Oct 31, 2017, 21:10 Chris Tessum <notifications@github.com> wrote:

> In the future you can do git push -f origin branchname to force the
> rewriting of the github version
>
> —
> You are receiving this because you modified the open/close state.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/ctessum/gobra/pull/4#issuecomment-340973400>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AEaAb4lclkb7U6qUsCeZMuRoKJmGmHpHks5sx-82gaJpZM4QLrCl>
> .
>